[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dunn"
authors = [{name = "msoodb", email = "masoud.bolhassani@gmail.com"}]
dynamic = ["version", "description"]
